main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('watches/', views.WatchList.as_view(), name='watches'),
    path('watches/<int:pk>/', views.WatchDetail.as_view(), name='watch_detail'),
    path('watches/create', views.WatchCreate.as_view(), name='watch_create'),
    path('watches/<int:pk>/edit/', views.WatchUpdate.as_view(), name='watch_update'),
    path('watches/<int:pk>/remove/', views.WatchDelete.as_view(), name='watch_remove'),
    path('watches/<int:watch_id>/add_photo/', views.add_photo, name='add_photo'),
    path('watches/<int:watch_id>/photos/<int:photo_id>/remove', views.remove_photo, name='remove_photo'),
    path('watches/<int:watch_id>/add_service/', views.add_service, name='add_service'),

    path('accessories/', views.AccessoryList.as_view(), name='accessory_list'),
    path('accessories/<int:pk>/', views.AccessoryDetail.as_view(), name="accessory_detail"),
    path('accessories/create/', views.AccessoryCreate.as_view(), name="accessory_create"),
    path('accessories/<int:pk>/update/', views.AccessoryUpdate.as_view(), name="accessory_update"),
    path('accessories/<int:pk>/delete/', views.AccessoryDelete.as_view(), name="accessory_delete"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/add_photo/', views.add_profile_photo, name='add_profile_photo'),
    path('profile/photo/remove', views.remove_profile_photo, name='remove_profile_photo'),
]

watchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [    
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

MOVEMENTS = (
    ('', ''),
    ('M', 'Mechanical'),
    ('Q', 'Quartz'),
)

class Accessory(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.CharField(max_length=500)

    def get_absolute_url(self):
        return reverse('accessory_detail', kwargs={'accessory_id': self.id})

# Create your models here.
class Watch(models.Model):
    make = models.CharField(max_length=100, default='')
    name = models.CharField(max_length=100, default='')
    model_ref = models.CharField(max_length=100, default='')
    serial_number = models.CharField(max_length=100)
    band_width = models.IntegerField(default=0)
    band_type = models.CharField(max_length=100, default='')
    band_color = models.CharField(max_length=100, default='')
    case_diameter = models.IntegerField(default=0)
    case_material = models.CharField(max_length=100, default='')
    other_materials = models.CharField(max_length=100, default='')
    watchface_color = models.CharField(max_length=100, default='')
    movement = models.CharField(
        max_length=100,
        choices=MOVEMENTS,
        default=MOVEMENTS[0][0],
    )
    thickness = models.FloatField(default=0.00)
    weight = models.FloatField(default=0.00)
    notes = models.TextField(default='')
    date_created = models.DateField(auto_now=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} with a {self.get_movement_display()} movement."
    
    def get_absolute_url(self):
        return reverse('watches_detail', kwargs={'watch_id': self.id})

class Service(models.Model):
    name = models.CharField(max_length=200)
    notes = models.TextField()
    watch = models.ForeignKey(Watch, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()

class Photo(models.Model):
    url = models.CharField(max_length=255)
    watch = models.ForeignKey(Watch, on_delete=models.CASCADE)

    def __str__(self):
        return self.url

class ProfilePhoto(models.Model):
    url = models.CharField(max_length=255)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.url

main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Service

class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'notes', 'timestamp']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
import boto3
import uuid
from .models import Watch, Accessory, ProfilePhoto, Photo, Service
from .forms import ServiceForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com'
BUCKET = ''

def signup(request):
    error_msg = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_msg = 'Invalid Credentials - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_msg': error_msg}
    return render(request, 'registration/signup.html', context)

@login_required
def profile(request):
    user = User.objects.get(id=request.user.id)
    watches = Watch.objects.filter(owner=request.user.id)
    if ProfilePhoto.objects.filter(user=request.user.id):
        return render(request, 'main_app/profile.html', {
            'user': user,
            'photos': ProfilePhoto.objects.filter(user=request.user.id),
            'watches': watches
        })
    return render(request, 'main_app/profile.html', {
            'user': user,
            'watches': watches
        })

def profile_edit(request):
    user = User.objects.get(id=request.user.id)
    return render(request, 'main_app/profile_edit.html', {
        'user': user
    })

def profile_update(request):
    user = User.objects.get(id=request.user.id)
    user.first_name = request.POST.get('first_name')
    user.last_name = request.POST.get('last_name')
    user.email = request.POST.get('email')
    user.save()
    print(dir(user))
    return redirect('profile')

class WatchList(LoginRequiredMixin, ListView):
    model = Watch
    fields = '__all__'
    context_object_name = 'watch_list'

class WatchCreate(LoginRequiredMixin, CreateView):
    model = Watch
    fields = ['name', 'make', 'model_ref', 'serial_number', 'band_width', 'band_type', 'band_color', 'case_diameter', 'case_material', 'other_materials', 'movement', 'thickness', 'weight', 'notes']
    success_url = '/watches/'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class WatchDetail(LoginRequiredMixin, DetailView):
    model = Watch
    fields = '__all__'
    form = ServiceForm


class WatchUpdate(LoginRequiredMixin, UpdateView):
    model = Watch
    fields = ['make', 'name', 'model_ref', 'serial_number', 'band_width', 'band_type', 'band_color', 'case_diameter', 'case_material', 'other_materials', 'watchface_color', 'movement', 'thickness', 'weight', 'notes']
    success_url = '/watches/'

class WatchDelete(LoginRequiredMixin, DeleteView):
    model = Watch
    success_url = '/watches/'

class AccessoryList(LoginRequiredMixin, ListView):
    model = Accessory
    context_object_name = 'accessories'

class AccessoryDetail(LoginRequiredMixin, DetailView):
    model = Accessory

class AccessoryCreate(LoginRequiredMixin, CreateView):
    model = Accessory
    fields = "__all__"
    success_url = '/accessories/'

class AccessoryUpdate(LoginRequiredMixin, UpdateView):
    model = Accessory
    fields = '__all__'
    success_url = '/accessories/'

class AccessoryDelete(LoginRequiredMixin, DeleteView):
    model = Accessory
    success_url = '/accessories/'



@login_required
def add_service(request, watch_id):
    form = ServiceForm(request.POST)

    if form.is_valid():
        new_service = form.save(commit=False)
        new_service.watch_id = watch_id
        new_service.save()
    return redirect('watch_detail', watch_id=watch_id)

# Create your views here.
def index(request):
    return render(request, 'index.html')

@login_required
def about(request):
    return render(request, 'about.html')

@login_required
def watches_index(request):
    watches = Watch.objects.all()
    return render(request, 'watches/index.html', {
        'watches': watches
    })

@login_required
def watches_detail(request, watch_id):
    watch = Watch.objects.get(id=watch_id)
    accessories = Accessory.objects.all()
    return render(request, 'watches/detail.html', {
        'watch': watch,
        'accessories': accessories,
    })

@login_required
def add_photo(request, watch_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        file_extension = photo_file.name[photo_file.name.rfind('.'):]
        key = uuid.uuid4().hex[:8] + file_extension

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}/{BUCKET}/{key}"
            photo = Photo(url=url, watch_id=watch_id)
            photo.save()
        except:
            print('Error while uploading file to s3')
    return redirect('watch_detail', watch_id)

@login_required
def add_profile_photo(request):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        file_extension = photo_file.name[photo_file.name.rfind('.'):]
        key = uuid.uuid4().hex[:8] + file_extension

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}/{BUCKET}/{key}"
            photo = ProfilePhoto(url=url, user_id=request.user.id)
            photo.save()
        except:
            print('Error while uploading file to s3')
    return redirect('profile')


def remove_photo(request, watch_id, photo_id):
    Photo.objects.get(id=photo_id).delete()
    return redirect('watch_detail', watch_id)

def remove_profile_photo(request):
    ProfilePhoto.objects.get(user=request.user.id).delete()
    return redirect('profile')

main_app/templates/main_app/accessory_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Confirm Delete</h1>
<h4>Are you sure you want to delete {{object.name}}</h4>
<form action="" method="POST">
    {%csrf_token%}
    <input type="submit" value="Yes - Delete" class="btn red">
</form>
{% endblock %}

main_app/templates/main_app/accessory_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{object.name}} Detail</h1>
    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <p><b>Price</b></p>
                    <p>${{object.price}}</p>
                    <br>
                    <p><b>Description</b></p>
                    <p>{{object.description}}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'accessory_delete' object.id %}">Delete</a>
                    <a href="{% url 'accessory_update' object.id %}">Edit</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main_app/templates/main_app/accessory_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
    <h1>Edit <span class='blue-text'>{{ object.name }}</span></h1>
{% else %}
    <h1>Add Accessory</h1>
{% endif %}
    <form action="" method="POST">
        {% csrf_token%}
        <table>    
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/accessory_list.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'accessory_create' %}"><button class="btn" style="float:right; margin-top: 65px;">Add Accessory</button></a>
<h1>Accessories</h1>
<hr>
<!-- {% if accessories.count %} -->
{% for accessory in accessories %}
<a href="/accessories/{{accessory.id}}/">
    <div class="card">
        <a href="{% url 'accessory_detail' accessory.id %}">
            <div class="card-content">
                <div class="row">
                <div class="col s2">
                    <img style="width: 100px; height: 100px;">
                </div>
                <div class="col s10">
                <span class="card-title">
                    <h4>{{ accessory.name }}</h4>
                </span>
                <p>${{accessory.price}}</p>
            </div>
            </div>
        </div>
        </a>
    </div>
</a>
{% endfor %}
<!-- {% else %} -->
<!-- <p>No Accesories Available</p> -->
<!-- {% endif %} -->
{% endblock %}

main_app/templates/main_app/profile.html
{% extends 'base.html' %} {% block content %}
<h1>{{user.get_full_name}}</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <a href="{% url 'profile_edit' %}" class="btn blue" id="profile-edit">Edit Profile</a>
            <div class="card-content" style="min-height: 200px;">
                <div id="profile-photo-upload" class="col s4">
                    {% if photos %}
                    <a href="{% url 'remove_profile_photo' %}">
                        <div class="profile-photo" style="background-image: url('{{photos.first }}');"></div>
                    </a>
                    {% else %}
                    <form action="{% url 'add_profile_photo' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="file" name="photo-file">
                        <br><br>
                        <input type="submit" class="btn green" value="Add Photo">
                    </form>
                    {% endif %}
                </div>
                <div class="col s8">
                    <p id=email-view>{{user.email}}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col s6">
        {% for watch in watches %}
        <a href="{% url 'watch_detail' watch.id %}">
            <div class="card">
                <div class="card-content">
                    <h5>{{watch.name}}</h5>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/main_app/profile_edit.html
{% extends 'base.html' %} {% block content %}
<h1>Edit <span class="grey-text">{{user.get_full_name}}</span></h1>
<div class="card-panel">
    <div class="card-content">
        <div class="row">

        </div>
        <form action="{% url 'profile_update' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col s6">
                    <input name="first_name" type="text" value="{{user.first_name}}">
                </div>
                <div class="col s6">
                    <input name="last_name" type="text" value="{{user.last_name}}">
                </div>
            </div>
            <input name="email" type="text" value="{{user.email}}">
            <br><br>
            <input type="submit" class="btn green" value="Update">
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/watch_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Confirm Delete</h1>

<h5>Are you sure you want to delete <b>{{ object.name }}</b></h5>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn green">
    <a class="btn red" href="{% url 'watch_detail' watch.id %}">No</a>
</form>
{% endblock %}

main_app/templates/main_app/watch_detail.html
{% extends 'base.html' %} {% block content %}
<h1><span>{{ watch.name }}</span></h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <p>
                    <b>Make: </b> {{ watch.make }}
                </p>
                <p>
                    <b>Model Reference: </b> {{ watch.model_ref }}
                </p>
                <p>
                    <b>Serial Number: </b> {{ watch.serial_number }}
                </p>
                <p>
                    <b>Case Diameter: </b> {{ watch.case_diameter }}mm
                </p>
                <p>
                    <b>Movement: </b> {{ watch.get_movement_display }}
                </p>
                <p>
                    <b>Notes: </b><br> {{ watch.notes }}
                </p>

                <p>{{ watch.get_movement_display }}</p>
            </div>
            {% if object.owner == user %}
            <div class="card-action">
                <a href="{% url 'watch_update' watch.id %}" class="blue-text">Edit</a>
                <a href="{% url 'watch_remove' watch.id %}" class="red-text">Delete</a>
            </div>
            {% endif %}
            </a>
        </div>
        <div class="card">
            <div class="card-content">
                <table>
                    <thead>
                        <th>Service</th>
                        <th>Date</th>
                    </thead>
                    <tbody>
                        {% for service in watch.service_set.all %}
                        <tr>
                            <td>{{service.name}}</td>
                            <td>{{service.timestamp|date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if object.owner == user %}
        <div class="card">
            <div class="card-content">
                <form action="{% url 'add_service' watch.id %}" method="POST">
                    {% csrf_token %}
                    <input name="name" type="text" placeholder="Service Name">
                    <textarea name="notes" placeholder="Notes"></textarea>
                    <input name="timestamp" type="date">
                    <input type="submit" class="btn green" value="Add Service">
                </form>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="col s6">
        {% if watch.owner == user %}
        <form action="{% url 'add_photo' watch.id %}" method="POST" enctype="multipart/form-data" class="card-panel">
            {% csrf_token %}
            <input type="file" name='photo-file'>
            <br><br>
            <input type="submit" class="btn green" value="Upload Image">
        </form>
        {% endif %} {% if watch.photo_set.all %} {% for photo in watch.photo_set.all %} {% if object.owner == user %}
        <a href="/watches/{{watch.id}}/photos/{{photo.id}}/remove">
            <img class="responsive-img card-panel" src="{{photo.url}}"></a> {% else %}
        <img class="card-panel" src="{{photo.url}}"></a>
        {% endif %} {% endfor %} {% endif %}
    </div>
</div>
{% endblock %}

main_app/templates/main_app/watch_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit {{ object.name }}</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <div class="card">
        <div class="card-content">
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit" class="btn green">
        </div>
    </div>
</form>
{% endblock %}

main_app/templates/main_app/watch_list.html
{% extends 'base.html' %} {% block content %}
<a href="{% url 'watch_create' %}"><button class="btn green" style="float:right; margin-top: 65px;">Add New Watch</button></a>
<h1>Watch Collection</h1>
{% for watch in watch_list %}
<div class="card card-medium">
    <a href="{% url 'watch_detail' watch.id %}">
        <div class="card-content">
            <div class="row">
                <div class="col s3">
                    <div id="title-image" style="background-image: url({{watch.photo_set.first}})">
                    </div>
                </div>
                <div class="col s9">
                    <span class="card-title">
                        <h4><b>{{watch.name}}</b></h4>
                        <h6>{{ watch.make }}</h6>
                        </span>
                    <p><b>Reference: </b>{{ watch.model_ref }}</p>
                </div>
            </div>
        </div>
    </a>
</div>
{% endfor %} {% endblock %}